In [2]:
!pip install datasets

Collecting datasets
  Downloading datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Collecting filelock (from datasets)
  Downloading filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Collecting numpy>=1.17 (from datasets)
  Downloading numpy-2.4.4-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-23.0.1-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting pandas (from datasets)
  Downloading pandas-3.0.2-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: requests>=2.32.2 in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (2.33.1)
Requirement already satisfied: httpx<1.0.0 in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (0.28.1)
Collecting tqdm>=4.66.3 (from datasets)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting xxhash (from datasets)
  Downloading xxhash-3.6.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Downloading multiprocess-0.70.19-py311-none-any.whl.metadata (7.5 kB)
Collecting fsspec<=2026.2.0,>=2023.1.0 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting huggingface-hub<2.0,>=0.25.0 (from datasets)
  Downloading huggingface_hub-1.9.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: packaging in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (6.0.3)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.5-cp311-cp311-win_amd64.whl.metadata (8.4 kB)
Requirement already satisfied: anyio in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in E:\conda\envs\mental_env\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading hf_xet-1.4.3-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting typer (from huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading yarl-1.23.0-cp311-cp311-win_amd64.whl.metadata (82 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in E:\conda\envs\mental_env\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.26 in E:\conda\envs\mental_env\Lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: colorama in E:\conda\envs\mental_env\Lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in E:\conda\envs\mental_env\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Collecting tzdata (from pandas->datasets)
  Downloading tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in E:\conda\envs\mental_env\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Collecting click>=8.2.1 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading click-8.3.2-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in E:\conda\envs\mental_env\Lib\site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading datasets-4.8.4-py3-none-any.whl (526 kB)
   ---------------------------------------- 0.0/527.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/527.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/527.0 kB ? eta -:--:--
   ------------------- -------------------- 262.1/527.0 kB ? eta -:--:--
   -------------------------------------  524.3/527.0 kB 799.2 kB/s eta 0:00:01
   ---------------------------------------- 527.0/527.0 kB 706.3 kB/s  0:00:00
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Downloading huggingface_hub-1.9.0-py3-none-any.whl (637 kB)
   ---------------------------------------- 0.0/637.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/637.4 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/637.4 kB ? eta -:--:--
   ---------------------------------------- 637.4/637.4 kB 924.2 kB/s  0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-win_amd64.whl (3.7 MB)
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.7 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/3.7 MB 882.6 kB/s eta 0:00:04
   -------- ------------------------------- 0.8/3.7 MB 931.2 kB/s eta 0:00:04
   ----------- ---------------------------- 1.0/3.7 MB 931.8 kB/s eta 0:00:03
   ----------- ---------------------------- 1.0/3.7 MB 931.8 kB/s eta 0:00:03
   -------------- ------------------------- 1.3/3.7 MB 932.1 kB/s eta 0:00:03
   -------------- ------------------------- 1.3/3.7 MB 932.1 kB/s eta 0:00:03
   ----------------- ---------------------- 1.6/3.7 MB 847.3 kB/s eta 0:00:03
   ----------------- ---------------------- 1.6/3.7 MB 847.3 kB/s eta 0:00:03
   ------------------- -------------------- 1.8/3.7 MB 756.9 kB/s eta 0:00:03
   ---------------------- ----------------- 2.1/3.7 MB 793.3 kB/s eta 0:00:02
   ------------------------- -------------- 2.4/3.7 MB 808.5 kB/s eta 0:00:02
   ---------------------------- ----------- 2.6/3.7 MB 824.9 kB/s eta 0:00:02
   ---------------------------- ----------- 2.6/3.7 MB 824.9 kB/s eta 0:00:02
   ------------------------------- -------- 2.9/3.7 MB 834.6 kB/s eta 0:00:01
   ---------------------------------- ----- 3.1/3.7 MB 846.6 kB/s eta 0:00:01
   ------------------------------------- -- 3.4/3.7 MB 856.7 kB/s eta 0:00:01
   ---------------------------------------  3.7/3.7 MB 862.1 kB/s eta 0:00:01
   ---------------------------------------- 3.7/3.7 MB 847.2 kB/s  0:00:04
Downloading multiprocess-0.70.19-py311-none-any.whl (144 kB)
Downloading aiohttp-3.13.5-cp311-cp311-win_amd64.whl (462 kB)
Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl (45 kB)
Downloading yarl-1.23.0-cp311-cp311-win_amd64.whl (87 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading filelock-3.25.2-py3-none-any.whl (26 kB)
Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl (44 kB)
Downloading numpy-2.4.4-cp311-cp311-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 932.9 kB/s eta 0:00:13
   -- ------------------------------------- 0.8/12.6 MB 931.2 kB/s eta 0:00:13
   --- ------------------------------------ 1.0/12.6 MB 949.8 kB/s eta 0:00:13
   --- ------------------------------------ 1.0/12.6 MB 949.8 kB/s eta 0:00:13
   ---- ----------------------------------- 1.3/12.6 MB 945.5 kB/s eta 0:00:12
   ---- ----------------------------------- 1.6/12.6 MB 902.1 kB/s eta 0:00:13
   ---- ----------------------------------- 1.6/12.6 MB 902.1 kB/s eta 0:00:13
   ----- ---------------------------------- 1.8/12.6 MB 853.0 kB/s eta 0:00:13
   ----- ---------------------------------- 1.8/12.6 MB 853.0 kB/s eta 0:00:13
   ----- ---------------------------------- 1.8/12.6 MB 853.0 kB/s eta 0:00:13
   ------ --------------------------------- 2.1/12.6 MB 699.0 kB/s eta 0:00:16
   ------ --------------------------------- 2.1/12.6 MB 699.0 kB/s eta 0:00:16
   ------ --------------------------------- 2.1/12.6 MB 699.0 kB/s eta 0:00:16
   ------ --------------------------------- 2.1/12.6 MB 699.0 kB/s eta 0:00:16
   ------ --------------------------------- 2.1/12.6 MB 699.0 kB/s eta 0:00:16
   ------ --------------------------------- 2.1/12.6 MB 699.0 kB/s eta 0:00:16
   --------- ------------------------------ 2.9/12.6 MB 693.3 kB/s eta 0:00:15
   --------- ------------------------------ 3.1/12.6 MB 726.5 kB/s eta 0:00:14
   ---------- ----------------------------- 3.4/12.6 MB 737.4 kB/s eta 0:00:13
   ----------- ---------------------------- 3.7/12.6 MB 754.6 kB/s eta 0:00:12
   ------------ --------------------------- 3.9/12.6 MB 765.1 kB/s eta 0:00:12
   ------------ --------------------------- 3.9/12.6 MB 765.1 kB/s eta 0:00:12
   ------------- -------------------------- 4.2/12.6 MB 771.9 kB/s eta 0:00:11
   -------------- ------------------------- 4.5/12.6 MB 780.3 kB/s eta 0:00:11
   -------------- ------------------------- 4.5/12.6 MB 780.3 kB/s eta 0:00:11
   -------------- ------------------------- 4.7/12.6 MB 756.5 kB/s eta 0:00:11
   -------------- ------------------------- 4.7/12.6 MB 756.5 kB/s eta 0:00:11
   --------------- ------------------------ 5.0/12.6 MB 751.2 kB/s eta 0:00:11
   --------------- ------------------------ 5.0/12.6 MB 751.2 kB/s eta 0:00:11
   --------------- ------------------------ 5.0/12.6 MB 751.2 kB/s eta 0:00:11
   ---------------- ----------------------- 5.2/12.6 MB 711.5 kB/s eta 0:00:11
   ---------------- ----------------------- 5.2/12.6 MB 711.5 kB/s eta 0:00:11
   ----------------- ---------------------- 5.5/12.6 MB 715.5 kB/s eta 0:00:10
   ------------------ --------------------- 5.8/12.6 MB 716.1 kB/s eta 0:00:10
   ------------------ --------------------- 5.8/12.6 MB 716.1 kB/s eta 0:00:10
   ------------------- -------------------- 6.0/12.6 MB 716.7 kB/s eta 0:00:10
   ------------------- -------------------- 6.0/12.6 MB 716.7 kB/s eta 0:00:10
   ------------------- -------------------- 6.3/12.6 MB 714.5 kB/s eta 0:00:09
   -------------------- ------------------- 6.6/12.6 MB 713.9 kB/s eta 0:00:09
   -------------------- ------------------- 6.6/12.6 MB 713.9 kB/s eta 0:00:09
   --------------------- ------------------ 6.8/12.6 MB 712.1 kB/s eta 0:00:09
   --------------------- ------------------ 6.8/12.6 MB 712.1 kB/s eta 0:00:09
   ---------------------- ----------------- 7.1/12.6 MB 708.1 kB/s eta 0:00:08
   ---------------------- ----------------- 7.1/12.6 MB 708.1 kB/s eta 0:00:08
   ---------------------- ----------------- 7.1/12.6 MB 708.1 kB/s eta 0:00:08
   ---------------------- ----------------- 7.1/12.6 MB 708.1 kB/s eta 0:00:08
   ---------------------- ----------------- 7.1/12.6 MB 708.1 kB/s eta 0:00:08
   ---------------------- ----------------- 7.1/12.6 MB 708.1 kB/s eta 0:00:08
   ---------------------- ----------------- 7.1/12.6 MB 708.1 kB/s eta 0:00:08
   ----------------------- ---------------- 7.3/12.6 MB 638.0 kB/s eta 0:00:09
   ------------------------ --------------- 7.6/12.6 MB 649.7 kB/s eta 0:00:08
   ------------------------ --------------- 7.6/12.6 MB 649.7 kB/s eta 0:00:08
   ------------------------ --------------- 7.9/12.6 MB 645.3 kB/s eta 0:00:08
   ------------------------- -------------- 8.1/12.6 MB 649.5 kB/s eta 0:00:07
   ------------------------- -------------- 8.1/12.6 MB 649.5 kB/s eta 0:00:07
   -------------------------- ------------- 8.4/12.6 MB 654.2 kB/s eta 0:00:07
   --------------------------- ------------ 8.7/12.6 MB 661.1 kB/s eta 0:00:06
   ---------------------------- ----------- 8.9/12.6 MB 667.0 kB/s eta 0:00:06
   ---------------------------- ----------- 8.9/12.6 MB 667.0 kB/s eta 0:00:06
   ----------------------------- ---------- 9.2/12.6 MB 671.1 kB/s eta 0:00:06
   ----------------------------- ---------- 9.4/12.6 MB 671.9 kB/s eta 0:00:05
   ----------------------------- ---------- 9.4/12.6 MB 671.9 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 669.6 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 669.6 kB/s eta 0:00:05
   ------------------------------- -------- 10.0/12.6 MB 665.3 kB/s eta 0:00:04
   ------------------------------- -------- 10.0/12.6 MB 665.3 kB/s eta 0:00:04
   ------------------------------- -------- 10.0/12.6 MB 665.3 kB/s eta 0:00:04
   -------------------------------- ------- 10.2/12.6 MB 662.0 kB/s eta 0:00:04
   -------------------------------- ------- 10.2/12.6 MB 662.0 kB/s eta 0:00:04
   --------------------------------- ------ 10.5/12.6 MB 658.9 kB/s eta 0:00:04
   ---------------------------------- ----- 10.7/12.6 MB 660.5 kB/s eta 0:00:03
   ---------------------------------- ----- 10.7/12.6 MB 660.5 kB/s eta 0:00:03
   ---------------------------------- ----- 11.0/12.6 MB 664.6 kB/s eta 0:00:03
   ---------------------------------- ----- 11.0/12.6 MB 664.6 kB/s eta 0:00:03
   ----------------------------------- ---- 11.3/12.6 MB 663.5 kB/s eta 0:00:03
   ------------------------------------ --- 11.5/12.6 MB 664.3 kB/s eta 0:00:02
   ------------------------------------ --- 11.5/12.6 MB 664.3 kB/s eta 0:00:02
   ------------------------------------- -- 11.8/12.6 MB 664.5 kB/s eta 0:00:02
   -------------------------------------- - 12.1/12.6 MB 667.5 kB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 667.5 kB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 668.2 kB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 673.4 kB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 669.4 kB/s  0:00:18
Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl (41 kB)
Downloading pyarrow-23.0.1-cp311-cp311-win_amd64.whl (27.5 MB)
   ---------------------------------------- 0.0/27.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.5 MB ? eta -:--:--
    --------------------------------------- 0.5/27.5 MB 882.6 kB/s eta 0:00:31
   - -------------------------------------- 0.8/27.5 MB 762.0 kB/s eta 0:00:36
   - -------------------------------------- 0.8/27.5 MB 762.0 kB/s eta 0:00:36
   - -------------------------------------- 1.0/27.5 MB 825.2 kB/s eta 0:00:33
   - -------------------------------------- 1.3/27.5 MB 838.9 kB/s eta 0:00:32
   -- ------------------------------------- 1.6/27.5 MB 873.8 kB/s eta 0:00:30
   -- ------------------------------------- 1.8/27.5 MB 875.3 kB/s eta 0:00:30
   -- ------------------------------------- 1.8/27.5 MB 875.3 kB/s eta 0:00:30
   --- ------------------------------------ 2.1/27.5 MB 896.4 kB/s eta 0:00:29
   --- ------------------------------------ 2.4/27.5 MB 860.2 kB/s eta 0:00:30
   --- ------------------------------------ 2.4/27.5 MB 860.2 kB/s eta 0:00:30
   --- ------------------------------------ 2.6/27.5 MB 853.0 kB/s eta 0:00:30
   --- ------------------------------------ 2.6/27.5 MB 853.0 kB/s eta 0:00:30
   ---- ----------------------------------- 2.9/27.5 MB 843.2 kB/s eta 0:00:30
   ---- ----------------------------------- 3.1/27.5 MB 835.1 kB/s eta 0:00:30
   ---- ----------------------------------- 3.1/27.5 MB 835.1 kB/s eta 0:00:30
   ---- ----------------------------------- 3.4/27.5 MB 835.3 kB/s eta 0:00:29
   ----- ---------------------------------- 3.7/27.5 MB 845.4 kB/s eta 0:00:29
   ----- ---------------------------------- 3.9/27.5 MB 850.9 kB/s eta 0:00:28
   ----- ---------------------------------- 3.9/27.5 MB 850.9 kB/s eta 0:00:28
   ------ --------------------------------- 4.2/27.5 MB 850.2 kB/s eta 0:00:28
   ------ --------------------------------- 4.5/27.5 MB 857.6 kB/s eta 0:00:27
   ------ --------------------------------- 4.7/27.5 MB 861.6 kB/s eta 0:00:27
   ------- -------------------------------- 5.0/27.5 MB 862.8 kB/s eta 0:00:27
   ------- -------------------------------- 5.0/27.5 MB 862.8 kB/s eta 0:00:27
   ------- -------------------------------- 5.2/27.5 MB 866.2 kB/s eta 0:00:26
   ------- -------------------------------- 5.5/27.5 MB 860.3 kB/s eta 0:00:26
   ------- -------------------------------- 5.5/27.5 MB 860.3 kB/s eta 0:00:26
   -------- ------------------------------- 5.8/27.5 MB 857.2 kB/s eta 0:00:26
   -------- ------------------------------- 6.0/27.5 MB 858.3 kB/s eta 0:00:26
   -------- ------------------------------- 6.0/27.5 MB 858.3 kB/s eta 0:00:26
   --------- ------------------------------ 6.3/27.5 MB 855.6 kB/s eta 0:00:25
   --------- ------------------------------ 6.3/27.5 MB 855.6 kB/s eta 0:00:25
   --------- ------------------------------ 6.3/27.5 MB 855.6 kB/s eta 0:00:25
   --------- ------------------------------ 6.8/27.5 MB 827.3 kB/s eta 0:00:26
   ---------- ----------------------------- 7.1/27.5 MB 850.3 kB/s eta 0:00:25
   ---------- ----------------------------- 7.3/27.5 MB 848.3 kB/s eta 0:00:24
   ---------- ----------------------------- 7.3/27.5 MB 848.3 kB/s eta 0:00:24
   ----------- ---------------------------- 7.6/27.5 MB 849.4 kB/s eta 0:00:24
   ----------- ---------------------------- 7.9/27.5 MB 849.1 kB/s eta 0:00:24
   ----------- ---------------------------- 8.1/27.5 MB 851.7 kB/s eta 0:00:23
   ----------- ---------------------------- 8.1/27.5 MB 851.7 kB/s eta 0:00:23
   ------------ --------------------------- 8.4/27.5 MB 855.4 kB/s eta 0:00:23
   ------------ --------------------------- 8.7/27.5 MB 859.0 kB/s eta 0:00:22
   ------------ --------------------------- 8.9/27.5 MB 861.0 kB/s eta 0:00:22

In [3]:
from datasets import load_dataset

dataset = load_dataset("moujar/MentalHealth-Darija")
df = dataset["train"].to_pandas()
print(df.head())

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

E:\conda\envs\mental_env\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\OS_10\.cache\huggingface\hub\datasets--moujar--MentalHealth-Darija. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

data.csv:   0%|          | 0.00/54.9M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/51093 [00:00<?, ? examples/s]

                                             text_en  \
0                                         oh my gosh
1  trouble sleeping, confused mind, restless hear...
2  All wrong, back off dear, forward doubt. Stay ...
3  I've shifted my focus to something else but I'...
4  I'm restless and restless, it's been a month n...

                                                text  label
0                                             يا ربي      0
1  مشكل فالنعاس، عقل محتار، قلب قلقان. كولشي خارج...      0
2  ماشي مشكل، رجع للور عزيزي، تقدم الشك. بقى فبلا...      0
3   بدلت التركيز ديالي لشي حاجة خرى ولكن مازال قلقان      0
4      انا مقلق وقلقان هادي شهر دابا ا ولدي اش كتقصد      0

In [4]:
import pandas as pd

df = dataset["train"].to_pandas()
print(df.head())

                                             text_en  \
0                                         oh my gosh
1  trouble sleeping, confused mind, restless hear...
2  All wrong, back off dear, forward doubt. Stay ...
3  I've shifted my focus to something else but I'...
4  I'm restless and restless, it's been a month n...

                                                text  label
0                                             يا ربي      0
1  مشكل فالنعاس، عقل محتار، قلب قلقان. كولشي خارج...      0
2  ماشي مشكل، رجع للور عزيزي، تقدم الشك. بقى فبلا...      0
3   بدلت التركيز ديالي لشي حاجة خرى ولكن مازال قلقان      0
4      انا مقلق وقلقان هادي شهر دابا ا ولدي اش كتقصد      0

In [5]:
df.to_csv("MentalHealth_Darija.csv", index=False)

In [7]:
pip install googletrans==4.0.0-rc1

Collecting googletrans==4.0.0-rc1
  Downloading googletrans-4.0.0rc1.tar.gz (20 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting httpx==0.13.3 (from googletrans==4.0.0-rc1)
  Downloading httpx-0.13.3-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: certifi in E:\conda\envs\mental_env\Lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2026.1.4)
Collecting hstspreload (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hstspreload-2025.1.1-py3-none-any.whl.metadata (2.1 kB)
Collecting sniffio (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting chardet==3.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading chardet-3.0.4-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting idna==2.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading idna-2.10-py2.py3-none-any.whl.metadata (9.1 kB)
Collecting rfc3986<2,>=1.3 (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting httpcore==0.9.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading httpcore-0.9.1-py3-none-any.whl.metadata (4.6 kB)
Collecting h11<0.10,>=0.8 (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading h11-0.9.0-py2.py3-none-any.whl.metadata (8.1 kB)
Collecting h2==3.* (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading h2-3.2.0-py2.py3-none-any.whl.metadata (32 kB)
Collecting hyperframe<6,>=5.2.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hyperframe-5.2.0-py2.py3-none-any.whl.metadata (7.2 kB)
Collecting hpack<4,>=3.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hpack-3.0.0-py2.py3-none-any.whl.metadata (7.0 kB)
Downloading httpx-0.13.3-py3-none-any.whl (55 kB)
Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Downloading httpcore-0.9.1-py3-none-any.whl (42 kB)
Downloading h11-0.9.0-py2.py3-none-any.whl (53 kB)
Downloading h2-3.2.0-py2.py3-none-any.whl (65 kB)
Downloading hpack-3.0.0-py2.py3-none-any.whl (38 kB)
Downloading hyperframe-5.2.0-py2.py3-none-any.whl (12 kB)
Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading hstspreload-2025.1.1-py3-none-any.whl (1.3 MB)
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   -------- ------------------------------- 0.3/1.3 MB ? eta -:--:--
   -------- ------------------------------- 0.3/1.3 MB ? eta -:--:--
   ---------------- ----------------------- 0.5/1.3 MB 558.9 kB/s eta 0:00:02
   ---------------- ----------------------- 0.5/1.3 MB 558.9 kB/s eta 0:00:02
   ---------------- ----------------------- 0.5/1.3 MB 558.9 kB/s eta 0:00:02
   ---------------- ----------------------- 0.5/1.3 MB 558.9 kB/s eta 0:00:02
   ------------------------ --------------- 0.8/1.3 MB 372.9 kB/s eta 0:00:02
   ------------------------ --------------- 0.8/1.3 MB 372.9 kB/s eta 0:00:02
   ------------------------ --------------- 0.8/1.3 MB 372.9 kB/s eta 0:00:02
   -------------------------------- ------- 1.0/1.3 MB 399.4 kB/s eta 0:00:01
   -------------------------------- ------- 1.0/1.3 MB 399.4 kB/s eta 0:00:01
   ---------------------------------------- 1.3/1.3 MB 408.9 kB/s  0:00:02
Building wheels for collected packages: googletrans
  Building wheel for googletrans (pyproject.toml): started
  Building wheel for googletrans (pyproject.toml): finished with status 'done'
  Created wheel for googletrans: filename=googletrans-4.0.0rc1-py3-none-any.whl size=17517 sha256=b287284538d73b01e2147a580b46fe263456b1379f37d829d100f7500d95dd1d
  Stored in directory: c:\users\os_10\appdata\local\pip\cache\wheels\39\17\6f\66a045ea3d168826074691b4b787b8f324d3f646d755443fda
Successfully built googletrans
Installing collected packages: rfc3986, hyperframe, hpack, h11, chardet, sniffio, idna, hstspreload, h2, httpcore, httpx, googletrans

   ----------------------------------------  0/12 [rfc3986]
   ----------------------------------------  0/12 [rfc3986]
   ----------------------------------------  0/12 [rfc3986]
   --- ------------------------------------  1/12 [hyperframe]
   ------ ---------------------------------  2/12 [hpack]
   ------ ---------------------------------  2/12 [hpack]
  Attempting uninstall: h11
   ------ ---------------------------------  2/12 [hpack]
    Found existing installation: h11 0.16.0
   ------ ---------------------------------  2/12 [hpack]
    Uninstalling h11-0.16.0:
   ------ ---------------------------------  2/12 [hpack]
      Successfully uninstalled h11-0.16.0
   ------ ---------------------------------  2/12 [hpack]
   ---------- -----------------------------  3/12 [h11]
   ---------- -----------------------------  3/12 [h11]
   ---------- -----------------------------  3/12 [h11]
   ---------- -----------------------------  3/12 [h11]
   ---------- -----------------------------  3/12 [h11]
   ---------- -----------------------------  3/12 [h11]
   ------------- --------------------------  4/12 [chardet]
   ------------- --------------------------  4/12 [chardet]
   ------------- --------------------------  4/12 [chardet]
   ------------- --------------------------  4/12 [chardet]
   ------------- --------------------------  4/12 [chardet]
   ------------- --------------------------  4/12 [chardet]
   ------------- --------------------------  4/12 [chardet]
   ------------- --------------------------  4/12 [chardet]
   ------------- --------------------------  4/12 [chardet]
   ---------------- -----------------------  5/12 [sniffio]
  Attempting uninstall: idna
   ---------------- -----------------------  5/12 [sniffio]
    Found existing installation: idna 3.11
   ---------------- -----------------------  5/12 [sniffio]
    Uninstalling idna-3.11:
   ---------------- -----------------------  5/12 [sniffio]
      Successfully uninstalled idna-3.11
   ---------------- -----------------------  5/12 [sniffio]
   -------------------- -------------------  6/12 [idna]
   -------------------- -------------------  6/12 [idna]
   -------------------- -------------------  6/12 [idna]
   -------------------------- -------------  8/12 [h2]
   -------------------------- -------------  8/12 [h2]
   -------------------------- -------------  8/12 [h2]
  Attempting uninstall: httpcore
   -------------------------- -------------  8/12 [h2]
    Found existing installation: httpcore 1.0.9
   -------------------------- -------------  8/12 [h2]
   ------------------------------ ---------  9/12 [httpcore]
    Uninstalling httpcore-1.0.9:
   ------------------------------ ---------  9/12 [httpcore]
      Successfully uninstalled httpcore-1.0.9
   ------------------------------ ---------  9/12 [httpcore]
   ------------------------------ ---------  9/12 [httpcore]
   ------------------------------ ---------  9/12 [httpcore]
   ------------------------------ ---------  9/12 [httpcore]
   ------------------------------ ---------  9/12 [httpcore]
  Attempting uninstall: httpx
   ------------------------------ ---------  9/12 [httpcore]
    Found existing installation: httpx 0.28.1
   ------------------------------ ---------  9/12 [httpcore]
   --------------------------------- ------ 10/12 [httpx]
    Uninstalling httpx-0.28.1:
   --------------------------------- ------ 10/12 [httpx]
   --------------------------------- ------ 10/12 [httpx]
      Successfully uninstalled httpx-0.28.1
   --------------------------------- ------ 10/12 [httpx]
   --------------------------------- ------ 10/12 [httpx]
   --------------------------------- ------ 10/12 [httpx]
   --------------------------------- ------ 10/12 [httpx]
   ------------------------------------ --- 11/12 [googletrans]
   ---------------------------------------- 12/12 [googletrans]

Successfully installed chardet-3.0.4 googletrans-4.0.0rc1 h11-0.9.0 h2-3.2.0 hpack-3.0.0 hstspreload-2025.1.1 httpcore-0.9.1 httpx-0.13.3 hyperframe-5.2.0 idna-2.10 rfc3986-1.5.0 sniffio-1.3.1
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
huggingface-hub 1.9.0 requires httpx<1,>=0.23.0, but you have httpx 0.13.3 which is incompatible.
jupyterlab 4.5.6 requires httpx<1,>=0.25.0, but you have httpx 0.13.3 which is incompatible.

In [9]:
pip install deep-translator

Collecting deep-translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in E:\conda\envs\mental_env\Lib\site-packages (from deep-translator) (4.14.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in E:\conda\envs\mental_env\Lib\site-packages (from deep-translator) (2.33.1)
Requirement already satisfied: soupsieve>=1.6.1 in E:\conda\envs\mental_env\Lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in E:\conda\envs\mental_env\Lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in E:\conda\envs\mental_env\Lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in E:\conda\envs\mental_env\Lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.10)
Requirement already satisfied: urllib3<3,>=1.26 in E:\conda\envs\mental_env\Lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in E:\conda\envs\mental_env\Lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2026.1.4)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
Installing collected packages: deep-translator
Successfully installed deep-translator-1.11.4
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd

df = pd.read_csv("/kaggle/input/datasets/tasneem33355/data33/MentalHealth_Darija.csv")

df = df[['text', 'text_en', 'label']].dropna()

df['combined_text'] = df['text_en'] + " [SEP] " + df['text']

print(df[['combined_text', 'label']].head())
print(df.shape)

                                       combined_text  label
0                            oh my gosh [SEP] يا ربي      0
1  trouble sleeping, confused mind, restless hear...      0
2  All wrong, back off dear, forward doubt. Stay ...      0
3  I've shifted my focus to something else but I'...      0
4  I'm restless and restless, it's been a month n...      0
(51093, 4)

In [12]:
print(df['label'].unique())

[0 1 2 3 4 5 6]

In [14]:
print(df[['label', 'text_en']].groupby('label').head(3))

       label                                            text_en
0          0                                         oh my gosh
1          0  trouble sleeping, confused mind, restless hear...
2          0  All wrong, back off dear, forward doubt. Stay ...
712        1      Gr gr dreaming of ex crush to be my game, God
713        1                                 wkwkwk what a joke
714        1  Leaves are also standby in front of the PC ......
6895       2  I recently went through a breakup and she said...
6896       2  I do not know how to navigate these feelings, ...
6897       2  So I have been with my bf for 5 months , and h...
6898       3  I am so exhausted of this. Just when I think I...
6900       3  I am 20 year old with some good friends but I ...
6903       3  it is looming around the corner again. It alwa...
27244      4  He said he had not felt that way before, sugge...
27246      4  My mom then hit me with the newspaper and it s...
27247      4  until i met my new boyfriend, he is amazing, h...
44966      5  What birth control are you on? I tried an IUD ...
44967      5  Hypersexuality I was diagnosed with bipolar un...
44968      5  Meditation I have been using the free meditati...
49253      6  Is there anyone interested in joining a group ...
49254      6  Anyone else have nothing in common with other ...
49255      6  Being a ghost would be my ideal form of existe...

In [15]:
df_filtered = df[df['label'].isin([0, 2, 3])].copy()

label_map = {
    3: "depression",
    0: "anxiety",
    2: "stress"
}

df_filtered['target'] = df_filtered['label'].map(label_map)

print(df_filtered['target'].value_counts())
print(df_filtered[['combined_text', 'target']].head())
print(df_filtered.shape)

target
stress        15094
depression    10644
anxiety        3623
Name: count, dtype: int64
                                       combined_text   target
0                            oh my gosh [SEP] يا ربي  anxiety
1  trouble sleeping, confused mind, restless hear...  anxiety
2  All wrong, back off dear, forward doubt. Stay ...  anxiety
3  I've shifted my focus to something else but I'...  anxiety
4  I'm restless and restless, it's been a month n...  anxiety
(29361, 5)

In [16]:
df_filtered['target'].value_counts()

target
stress        15094
depression    10644
anxiety        3623
Name: count, dtype: int64

In [7]:
pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in E:\conda\envs\mental_env\Lib\site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 670.4 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/8.1 MB 670.4 kB/s eta 0:00:12
   --- ------------------------------------ 0.8/8.1 MB 684.4 kB/s eta 0:00:11
   ----- ---------------------------------- 1.0/8.1 MB 739.8 kB/s eta 0:00:10
   ------ --------------------------------- 1.3/8.1 MB 753.8 kB/s eta 0:00:09
   ------ --------------------------------- 1.3/8.1 MB 753.8 kB/s eta 0:00:09
   ------- -------------------------------- 1.6/8.1 MB 769.2 kB/s eta 0:00:09
   --------- ------------------------------ 1.8/8.1 MB 786.4 kB/s eta 0:00:08
   --------- ------------------------------ 1.8/8.1 MB 786.4 kB/s eta 0:00:08
   ---------- ----------------------------- 2.1/8.1 MB 793.3 kB/s eta 0:00:08
   ----------- ---------------------------- 2.4/8.1 MB 803.5 kB/s eta 0:00:08
   ----------- ---------------------------- 2.4/8.1 MB 803.5 kB/s eta 0:00:08
   ------------ --------------------------- 2.6/8.1 MB 807.4 kB/s eta 0:00:07
   -------------- ------------------------- 2.9/8.1 MB 810.3 kB/s eta 0:00:07
   --------------- ------------------------ 3.1/8.1 MB 816.4 kB/s eta 0:00:07
   --------------- ------------------------ 3.1/8.1 MB 816.4 kB/s eta 0:00:07
   ---------------- ----------------------- 3.4/8.1 MB 818.3 kB/s eta 0:00:06
   ------------------ --------------------- 3.7/8.1 MB 823.0 kB/s eta 0:00:06
   ------------------ --------------------- 3.7/8.1 MB 823.0 kB/s eta 0:00:06
   ------------------- -------------------- 3.9/8.1 MB 824.0 kB/s eta 0:00:06
   -------------------- ------------------- 4.2/8.1 MB 825.0 kB/s eta 0:00:05
   ---------------------- ----------------- 4.5/8.1 MB 828.4 kB/s eta 0:00:05
   ---------------------- ----------------- 4.5/8.1 MB 828.4 kB/s eta 0:00:05
   ----------------------- ---------------- 4.7/8.1 MB 831.4 kB/s eta 0:00:05
   ------------------------ --------------- 5.0/8.1 MB 831.9 kB/s eta 0:00:04
   ------------------------ --------------- 5.0/8.1 MB 831.9 kB/s eta 0:00:04
   ------------------------- -------------- 5.2/8.1 MB 832.2 kB/s eta 0:00:04
   --------------------------- ------------ 5.5/8.1 MB 834.6 kB/s eta 0:00:04
   --------------------------- ------------ 5.5/8.1 MB 834.6 kB/s eta 0:00:04
   ---------------------------- ----------- 5.8/8.1 MB 834.9 kB/s eta 0:00:03
   ----------------------------- ---------- 6.0/8.1 MB 836.9 kB/s eta 0:00:03
   ------------------------------- -------- 6.3/8.1 MB 836.9 kB/s eta 0:00:03
   ------------------------------- -------- 6.3/8.1 MB 836.9 kB/s eta 0:00:03
   -------------------------------- ------- 6.6/8.1 MB 837.1 kB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.1 MB 838.8 kB/s eta 0:00:02
   ----------------------------------- ---- 7.1/8.1 MB 838.9 kB/s eta 0:00:02
   ----------------------------------- ---- 7.1/8.1 MB 838.9 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.1 MB 840.4 kB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 840.3 kB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 840.3 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 841.7 kB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 834.1 kB/s  0:00:09
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
    --------------------------------------- 0.5/36.6 MB 840.2 kB/s eta 0:00:43
    --------------------------------------- 0.5/36.6 MB 840.2 kB/s eta 0:00:43
    --------------------------------------- 0.8/36.6 MB 860.9 kB/s eta 0:00:42
   - -------------------------------------- 1.0/36.6 MB 853.0 kB/s eta 0:00:42
   - -------------------------------------- 1.0/36.6 MB 853.0 kB/s eta 0:00:42
   - -------------------------------------- 1.3/36.6 MB 860.2 kB/s eta 0:00:42
   - -------------------------------------- 1.6/36.6 MB 839.1 kB/s eta 0:00:42
   - -------------------------------------- 1.6/36.6 MB 839.1 kB/s eta 0:00:42
   -- ------------------------------------- 1.8/36.6 MB 846.1 kB/s eta 0:00:42
   -- ------------------------------------- 2.1/36.6 MB 844.8 kB/s eta 0:00:41
   -- ------------------------------------- 2.4/36.6 MB 844.3 kB/s eta 0:00:41
   -- ------------------------------------- 2.4/36.6 MB 844.3 kB/s eta 0:00:41
   -- ------------------------------------- 2.6/36.6 MB 848.4 kB/s eta 0:00:41
   --- ------------------------------------ 2.9/36.6 MB 847.3 kB/s eta 0:00:40
   --- ------------------------------------ 2.9/36.6 MB 847.3 kB/s eta 0:00:40
   --- ------------------------------------ 3.1/36.6 MB 850.6 kB/s eta 0:00:40
   --- ------------------------------------ 3.4/36.6 MB 849.5 kB/s eta 0:00:40
   --- ------------------------------------ 3.4/36.6 MB 849.5 kB/s eta 0:00:40
   ---- ----------------------------------- 3.7/36.6 MB 852.0 kB/s eta 0:00:39
   ---- ----------------------------------- 3.9/36.6 MB 851.1 kB/s eta 0:00:39
   ---- ----------------------------------- 3.9/36.6 MB 851.1 kB/s eta 0:00:39
   ---- ----------------------------------- 4.2/36.6 MB 853.1 kB/s eta 0:00:38
   ---- ----------------------------------- 4.5/36.6 MB 852.2 kB/s eta 0:00:38
   ----- ---------------------------------- 4.7/36.6 MB 853.9 kB/s eta 0:00:38
   ----- ---------------------------------- 4.7/36.6 MB 853.9 kB/s eta 0:00:38
   ----- ---------------------------------- 5.0/36.6 MB 853.1 kB/s eta 0:00:38
   ----- ---------------------------------- 5.2/36.6 MB 854.6 kB/s eta 0:00:37
   ----- ---------------------------------- 5.2/36.6 MB 854.6 kB/s eta 0:00:37
   ------ --------------------------------- 5.5/36.6 MB 851.7 kB/s eta 0:00:37
   ------ --------------------------------- 5.5/36.6 MB 851.7 kB/s eta 0:00:37
   ------ --------------------------------- 5.5/36.6 MB 851.7 kB/s eta 0:00:37
   ------ --------------------------------- 6.0/36.6 MB 833.2 kB/s eta 0:00:37
   ------ --------------------------------- 6.0/36.6 MB 833.2 kB/s eta 0:00:37
   ------ --------------------------------- 6.3/36.6 MB 829.9 kB/s eta 0:00:37
   ------- -------------------------------- 6.6/36.6 MB 830.2 kB/s eta 0:00:37
   ------- -------------------------------- 6.6/36.6 MB 830.2 kB/s eta 0:00:37
   ------- -------------------------------- 6.8/36.6 MB 830.6 kB/s eta 0:00:36
   ------- -------------------------------- 7.1/36.6 MB 830.9 kB/s eta 0:00:36
   -------- ------------------------------- 7.3/36.6 MB 832.7 kB/s eta 0:00:36
   -------- ------------------------------- 7.3/36.6 MB 832.7 kB/s eta 0:00:36
   -------- ------------------------------- 7.6/36.6 MB 834.4 kB/s eta 0:00:35
   -------- ------------------------------- 7.9/36.6 MB 836.0 kB/s eta 0:00:35
   -------- ------------------------------- 7.9/36.6 MB 836.0 kB/s eta 0:00:35
   -------- ------------------------------- 8.1/36.6 MB 836.1 kB/s eta 0:00:35
   -------- ------------------------------- 8.1/36.6 MB 836.1 kB/s eta 0:00:35
   --------- ------------------------------ 8.4/36.6 MB 816.5 kB/s eta 0:00:35
   --------- ------------------------------ 8.7/36.6 MB 818.4 kB/s eta 0:00:35
   --------- ------------------------------ 8.7/36.6 MB 818.4 kB/s eta 0:00:35
   --------- ------------------------------ 8.9/36.6 MB 820.2 kB/s eta 0:00:34
   ---------- ----------------------------- 9.2/36.6 MB 820.8 kB/s eta 0:00:34
   ---------- ----------------------------- 9.2/36.6 MB 820.8 kB/s eta 0:00:34
   ---------- ----------------------------- 9.4/36.6 MB 822.4 kB/s eta 0:00:34
   ---------- ----------------------------- 9.4/36.6 MB 822.4 kB/s eta 0:00:34
   ---------- ----------------------------- 9.4/36.6 MB 822.4 kB/s eta 0:00:34
   ---------- ----------------------------- 9.4/36.6 MB 822.4 kB/s eta 0:00:34
   ---------- ----------------------------- 10.0/36.6 MB 805.1 kB/s eta 0:00:34
   ----------- ---------------------------- 10.2/36.6 MB 813.2 kB/s eta 0:00:33
   ----------- ---------------------------- 10.5/36.6 MB 812.8 kB/s eta 0:00:33
   ----------- ---------------------------- 10.5/36.6 MB 812.8 kB/s eta 0:00:33
   ----------- ---------------------------- 10.7/36.6 MB 814.4 kB/s eta 0:00:32
   ------------ --------------------------- 11.0/36.6 MB 815.0 kB/s eta 0:00:32
   ------------ --------------------------- 11.3/36.6 MB 816.5 kB/s eta 0:00:32
   ------------ --------------------------- 11.3/36.6 MB 816.5 kB/s eta 0:00:32
   ------------ --------------------------- 11.5/36.6 MB 817.0 kB/s eta 0:00:31
   ------------ --------------------------- 11.8/36.6 MB 818.4 kB/s eta 0:00:31
   ------------ --------------------------- 11.8/36.6 MB 818.4 kB/s eta 0:00:31
   ------------- -------------------------- 12.1/36.6 MB 818.0 kB/s eta 0:00:31
   ------------- -------------------------- 12.3/36.6 MB 820.1 kB/s eta 0:00:30
   ------------- -------------------------- 12.6/36.6 MB 820.6 kB/s eta 0:00:30
   ------------- -------------------------- 12.6/36.6 MB 820.6 kB/s eta 0:00:30
   -------------- ------------------------- 12.8/36.6 MB 820.9 kB/s eta 0:00:29
   -------------- ------------------------- 13.1/36.6 MB 820.5 kB/s eta 0:00:29
   -------------- ------------------------- 13.1/36.6 MB 820.5 kB/s eta 0:00:29
   -------------- ------------------------- 13.4/36.6 MB 820.0 kB/s eta 0:00:29
   -------------- ------------------------- 13.6/36.6 MB 821.2 kB/s eta 0:00:28
   -------------- ------------------------- 13.6/36.6 MB 821.2 kB/s eta 0:00:28
   --------------- ------------------------ 13.9/36.6 MB 815.3 kB/s eta 0:00:28
   --------------- ------------------------ 13.9/36.6 MB 815.3 kB/s eta 0:00:28
   --------------- ------------------------ 14.2/36.6 MB 814.3 kB/s eta 0:00:28
   --------------- ------------------------ 14.4/36.6 MB 817.7 kB/s eta 0:00:28
   ---------------- ----------------------- 14.7/36.6 MB 818.8 kB/s eta 0:00:27
   ---------------- ----------------------- 14.7/36.6 MB 818.8 kB/s eta 0:00:27
   ---------------- ----------------------- 14.9/36.6 MB 818.4 kB/s eta 0:00:27
   ---------------- ----------------------- 15.2/36.6 MB 819.5 kB/s eta 0:00:27
   ---------------- ----------------------- 15.2/36.6 MB 819.5 kB/s eta 0:00:27
   ---------------- ----------------------- 15.5/36.6 MB 817.0 kB/s eta 0:00:26
   ----------------- ---------------------- 15.7/36.6 MB 816.0 kB/s eta 0:00:26
   ----------------- ---------------------- 15.7/36.6 MB 816.0 kB/s eta 0:00:26
   ----------------- ---------------------- 16.0/36.6 MB 815.1 kB/s eta 0:00:26
   ----------------- ---------------------- 16.3/36.6 MB 817.4 kB/s eta 0:00:25
   ----------------- ---------------------- 16.3/36.6 MB 817.4 kB/s eta 0:00:25
   ------------------ --------------------- 16.5/36.6 MB 816.5 kB/s eta 0:00:25
   ------------------ --------------------- 16.8/36.6 MB 818.7 kB/s eta 0:00:25
   ------------------ --------------------- 16.8/36.6 MB 818.7 kB/s eta 0:00:25
   ------------------ --------------------- 17.0/36.6 MB 816.5 kB/s eta 0:00:24
   ------------------ --------------------- 17.3/36.6 MB 815.7 kB/s eta 0:00:24
   ------------------ --------------------- 17.3/36.6 MB 815.7 kB/s eta 0:00:24
   ------------------- -------------------- 17.6/36.6 MB 816.6 kB/s eta 0:00:24
   ------------------- -------------------- 17.8/36.6 MB 817.5 kB/s eta 0:00:23
   ------------------- -------------------- 18.1/36.6 MB 817.8 kB/s eta 0:00:23
   ------------------- -------------------- 18.1/36.6 MB 817.8 kB/s eta 0:00:23
   -------------------- ------------------- 18.4/36.6 MB 818.7 kB/s eta 0:00:23
   -------------------- ------------------- 18.4/36.6 MB 818.7 kB/s eta 0:00:23
   -------------------- ------------------- 18.4/36.6 MB 818.7 kB/s eta 0:00:23
   -------------------- ------------------- 18.4/36.6 MB 818.7 kB/s eta 0:00:23
   -------------------- ------------------- 18.4/36.6 MB 818.7 kB/s eta 0:00:23
   -------------------- ------------------- 18.9/36.6 MB 797.8 kB/s eta 0:00:23
   -------------------- ------------------- 19.1/36.6 MB 805.3 kB/s eta 0:00:22
   -------------------- ------------------- 19.1/36.6 MB 805.3 kB/s eta 0:00:22
   --------------------- ------------------ 19.4/36.6 MB 798.4 kB/s eta 0:00:22
   --------------------- ------------------ 19.4/36.6 MB 798.4 kB/s eta 0:00:22
   --------------------- ------------------ 19.7/36.6 MB 796.9 kB/s eta 0:00:22
   --------------------- ------------------ 19.9/36.6 MB 797.9 kB/s eta 0:00:21
   --------------------- ------------------ 19.9/36.6 MB 797.9 kB/s eta 0:00:21
   ---------------------- ----------------- 20.2/36.6 MB 798.9 kB/s eta 0:00:21
   ---------------------- ----------------- 20.2/36.6 MB 798.9 kB/s eta 0:00:21
   ---------------------- ----------------- 20.4/36.6 MB 796.9 kB/s eta 0:00:21
   ---------------------- ----------------- 20.7/36.6 MB 797.9 kB/s eta 0:00:20
   ---------------------- ----------------- 20.7/36.6 MB 797.9 kB/s eta 0:00:20
   ---------------------- ----------------- 20.7/36.6 MB 797.9 kB/s eta 0:00:20
   ---------------------- ----------------- 20.7/36.6 MB 797.9 kB/s eta 0:00:20
   ----------------------- ---------------- 21.2/36.6 MB 792.3 kB/s eta 0:00:20
   ----------------------- ---------------- 21.5/36.6 MB 791.9 kB/s eta 0:00:20
   ----------------------- ---------------- 21.5/36.6 MB 791.9 kB/s eta 0:00:20
   ----------------------- ---------------- 21.5/36.6 MB 791.9 kB/s eta 0:00:20
   ----------------------- ---------------- 21.8/36.6 MB 785.7 kB/s eta 0:00:19
   ----------------------- ---------------- 21.8/36.6 MB 785.7 kB/s eta 0:00:19
   ----------------------- ---------------- 21.8/36.6 MB 785.7 kB/s eta 0:00:19
   ----------------------- ---------------- 21.8/36.6 MB 785.7 kB/s eta 0:00:19
   ------------------------ --------------- 22.0/36.6 MB 767.2 kB/s eta 0:00:20
   ------------------------ --------------- 22.3/36.6 MB 773.9 kB/s eta 0:00:19
   ------------------------ --------------- 22.3/36.6 MB 773.9 kB/s eta 0:00:19
   ------------------------ --------------- 22.3/36.6 MB 773.9 kB/s eta 0:00:19
   ------------------------ --------------- 22.5/36.6 MB 764.2 kB/s eta 0:00:19
   ------------------------ --------------- 22.5/36.6 MB 764.2 kB/s eta 0:00:19
   ------------------------ --------------- 22.5/36.6 MB 764.2 kB/s eta 0:00:19
   ------------------------ --------------- 22.8/36.6 MB 757.0 kB/s eta 0:00:19
   ------------------------ --------------- 22.8/36.6 MB 757.0 kB/s eta 0:00:19
   ------------------------- -------------- 23.1/36.6 MB 754.6 kB/s eta 0:00:18
   ------------------------- -------------- 23.1/36.6 MB 754.6 kB/s eta 0:00:18
   ------------------------- -------------- 23.1/36.6 MB 754.6 kB/s eta 0:00:18
   ------------------------- -------------- 23.3/36.6 MB 745.8 kB/s eta 0:00:18
   ------------------------- -------------- 23.3/36.6 MB 745.8 kB/s eta 0:00:18
   ------------------------- -------------- 23.3/36.6 MB 745.8 kB/s eta 0:00:18
   ------------------------- -------------- 23.6/36.6 MB 736.7 kB/s eta 0:00:18
   ------------------------- -------------- 23.6/36.6 MB 736.7 kB/s eta 0:00:18
   -------------------------- ------------- 23.9/36.6 MB 730.2 kB/s eta 0:00:18
   -------------------------- ------------- 23.9/36.6 MB 730.2 kB/s eta 0:00:18
   -------------------------- ------------- 23.9/36.6 MB 730.2 kB/s eta 0:00:18
   -------------------------- ------------- 24.1/36.6 MB 721.8 kB/s eta 0:00:18
   -------------------------- ------------- 24.1/36.6 MB 721.8 kB/s eta 0:00:18
   -------------------------- ------------- 24.4/36.6 MB 716.5 kB/s eta 0:00:18
   -------------------------- ------------- 24.4/36.6 MB 716.5 kB/s eta 0:00:18
   -------------------------- ------------- 24.4/36.6 MB 716.5 kB/s eta 0:00:18
   -------------------------- ------------- 24.6/36.6 MB 709.3 kB/s eta 0:00:17
   -------------------------- ------------- 24.6/36.6 MB 709.3 kB/s eta 0:00:17
   -------------------------- ------------- 24.6/36.6 MB 709.3 kB/s eta 0:00:17
   --------------------------- ------------ 24.9/36.6 MB 693.5 kB/s eta 0:00:17
   --------------------------- ------------ 24.9/36.6 MB 693.5 kB/s eta 0:00:17
   --------------------------- ------------ 25.2/36.6 MB 694.3 kB/s eta 0:00:17
   --------------------------- ------------ 25.2/36.6 MB 694.3 kB/s eta 0:00:17
   --------------------------- ------------ 25.2/36.6 MB 694.3 kB/s eta 0:00:17
   --------------------------- ------------ 25.4/36.6 MB 684.8 kB/s eta 0:00:17
   --------------------------- ------------ 25.4/36.6 MB 684.8 kB/s eta 0:00:17
   --------------------------- ------------ 25.4/36.6 MB 684.8 kB/s eta 0:00:17
   --------------------------- ------------ 25.4/36.6 MB 684.8 kB/s eta 0:00:17
   --------------------------- ------------ 25.4/36.6 MB 684.8 kB/s eta 0:00:17
   --------------------------- ------------ 25.4/36.6 MB 684.8 kB/s eta 0:00:17
   --------------------------- ------------ 25.4/36.6 MB 684.8 kB/s eta 0:00:17
   --------------------------- ------------ 25.4/36.6 MB 684.8 kB/s eta 0:00:17
   ---------------------------- ----------- 25.7/36.6 MB 649.7 kB/s eta 0:00:17
   ---------------------------- ----------- 25.7/36.6 MB 649.7 kB/s eta 0:00:17
   ---------------------------- ----------- 26.0/36.6 MB 641.2 kB/s eta 0:00:17
   ---------------------------- ----------- 26.0/36.6 MB 641.2 kB/s eta 0:00:17
   ---------------------------- ----------- 26.0/36.6 MB 641.2 kB/s eta 0:00:17
   ---------------------------- ----------- 26.2/36.6 MB 632.4 kB/s eta 0:00:17
   ---------------------------- ----------- 26.2/36.6 MB 632.4 kB/s eta 0:00:17
   ---------------------------- ----------- 26.2/36.6 MB 632.4 kB/s eta 0:00:17
   ---------------------------- ----------- 26.2/36.6 MB 632.4 kB/s eta 0:00:17
   ---------------------------- ----------- 26.2/36.6 MB 632.4 kB/s eta 0:00:17
   ---------------------------- ----------- 26.5/36.6 MB 612.2 kB/s eta 0:00:17
   ---------------------------- ----------- 26.5/36.6 MB 612.2 kB/s eta 0:00:17
   ---------------------------- ----------- 26.5/36.6 MB 612.2 kB/s eta 0:00:17
   ---------------------------- ----------- 26.5/36.6 MB 612.2 kB/s eta 0:00:17
   ---------------------------- ----------- 26.5/36.6 MB 612.2 kB/s eta 0:00:17
   ----------------------------- ---------- 26.7/36.6 MB 590.7 kB/s eta 0:00:17
   ----------------------------- ---------- 26.7/36.6 MB 590.7 kB/s eta 0:00:17
   ----------------------------- ---------- 26.7/36.6 MB 590.7 kB/s eta 0:00:17
   ----------------------------- ---------- 26.7/36.6 MB 590.7 kB/s eta 0:00:17
   ----------------------------- ---------- 26.7/36.6 MB 590.7 kB/s eta 0:00:17
   ----------------------------- ---------- 26.7/36.6 MB 590.7 kB/s eta 0:00:17
   ----------------------------- ---------- 27.0/36.6 MB 577.6 kB/s eta 0:00:17
   ----------------------------- ---------- 27.0/36.6 MB 577.6 kB/s eta 0:00:17

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df_filtered['label_encoded'] = le.fit_transform(df_filtered['target'])

X_train, X_val, y_train, y_val = train_test_split(
    df_filtered['combined_text'],
    df_filtered['label_encoded'],
    test_size=0.2,
    random_state=42,
    stratify=df_filtered['label_encoded']
)

print(le.classes_)
print(X_train.shape, X_val.shape)
print(y_train.value_counts())

['anxiety' 'depression' 'stress']
(23488,) (5873,)
label_encoded
2    12075
1     8515
0     2898
Name: count, dtype: int64

In [10]:
pip install transformers datasets sentencepiece

Collecting transformers
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: datasets in E:\conda\envs\mental_env\Lib\site-packages (4.8.4)
Collecting sentencepiece
  Downloading sentencepiece-0.2.1-cp311-cp311-win_amd64.whl.metadata (10 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (1.9.0)
Requirement already satisfied: numpy>=1.17 in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (2.4.4)
Requirement already satisfied: packaging>=20.0 in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (6.0.3)
Collecting regex>=2025.10.22 (from transformers)
  Downloading regex-2026.4.4-cp311-cp311-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typer in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (0.24.1)
Collecting safetensors>=0.4.3 (from transformers)
  Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm>=4.27 in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Collecting httpx<1,>=0.23.0 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2.10)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: pyarrow>=21.0.0 in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (3.0.2)
Requirement already satisfied: requests>=2.32.2 in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (2.33.1)
Requirement already satisfied: xxhash in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in E:\conda\envs\mental_env\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in E:\conda\envs\mental_env\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.26 in E:\conda\envs\mental_env\Lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: colorama in E:\conda\envs\mental_env\Lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in E:\conda\envs\mental_env\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in E:\conda\envs\mental_env\Lib\site-packages (from pandas->datasets) (2026.1)
Requirement already satisfied: six>=1.5 in E:\conda\envs\mental_env\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in E:\conda\envs\mental_env\Lib\site-packages (from typer->transformers) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in E:\conda\envs\mental_env\Lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in E:\conda\envs\mental_env\Lib\site-packages (from typer->transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in E:\conda\envs\mental_env\Lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in E:\conda\envs\mental_env\Lib\site-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in E:\conda\envs\mental_env\Lib\site-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in E:\conda\envs\mental_env\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.5.0-py3-none-any.whl (10.2 MB)
   ---------------------------------------- 0.0/10.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/10.2 MB 882.6 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/10.2 MB 882.6 kB/s eta 0:00:12
   --- ------------------------------------ 0.8/10.2 MB 882.6 kB/s eta 0:00:11
   ---- ----------------------------------- 1.0/10.2 MB 868.0 kB/s eta 0:00:11
   ---- ----------------------------------- 1.0/10.2 MB 868.0 kB/s eta 0:00:11
   ----- ---------------------------------- 1.3/10.2 MB 871.6 kB/s eta 0:00:11
   ----- ---------------------------------- 1.3/10.2 MB 871.6 kB/s eta 0:00:11
   ------ --------------------------------- 1.6/10.2 MB 798.7 kB/s eta 0:00:11
   ------- -------------------------------- 1.8/10.2 MB 812.0 kB/s eta 0:00:11
   -------- ------------------------------- 2.1/10.2 MB 815.6 kB/s eta 0:00:10
   -------- ------------------------------- 2.1/10.2 MB 815.6 kB/s eta 0:00:10
   --------- ------------------------------ 2.4/10.2 MB 823.4 kB/s eta 0:00:10
   --------- ------------------------------ 2.4/10.2 MB 823.4 kB/s eta 0:00:10
   --------- ------------------------------ 2.4/10.2 MB 823.4 kB/s eta 0:00:10
   --------- ------------------------------ 2.4/10.2 MB 823.4 kB/s eta 0:00:10
   ----------- ---------------------------- 2.9/10.2 MB 745.6 kB/s eta 0:00:10
   ----------- ---------------------------- 2.9/10.2 MB 745.6 kB/s eta 0:00:10
   ------------ --------------------------- 3.1/10.2 MB 747.2 kB/s eta 0:00:10
   ------------- -------------------------- 3.4/10.2 MB 754.0 kB/s eta 0:00:10
   ------------- -------------------------- 3.4/10.2 MB 754.0 kB/s eta 0:00:10
   -------------- ------------------------- 3.7/10.2 MB 747.0 kB/s eta 0:00:09
   -------------- ------------------------- 3.7/10.2 MB 747.0 kB/s eta 0:00:09
   --------------- ------------------------ 3.9/10.2 MB 738.6 kB/s eta 0:00:09
   ---------------- ----------------------- 4.2/10.2 MB 744.6 kB/s eta 0:00:09
   ---------------- ----------------------- 4.2/10.2 MB 744.6 kB/s eta 0:00:09
   ----------------- ---------------------- 4.5/10.2 MB 739.5 kB/s eta 0:00:08
   ----------------- ---------------------- 4.5/10.2 MB 739.5 kB/s eta 0:00:08
   ------------------ --------------------- 4.7/10.2 MB 731.3 kB/s eta 0:00:08
   ------------------ --------------------- 4.7/10.2 MB 731.3 kB/s eta 0:00:08
   ------------------- -------------------- 5.0/10.2 MB 724.2 kB/s eta 0:00:08
   ------------------- -------------------- 5.0/10.2 MB 724.2 kB/s eta 0:00:08
   ------------------- -------------------- 5.0/10.2 MB 724.2 kB/s eta 0:00:08
   ------------------- -------------------- 5.0/10.2 MB 724.2 kB/s eta 0:00:08
   --------------------- ------------------ 5.5/10.2 MB 718.5 kB/s eta 0:00:07
   ---------------------- ----------------- 5.8/10.2 MB 722.0 kB/s eta 0:00:07
   ---------------------- ----------------- 5.8/10.2 MB 722.0 kB/s eta 0:00:07
   ----------------------- ---------------- 6.0/10.2 MB 712.5 kB/s eta 0:00:06
   ----------------------- ---------------- 6.0/10.2 MB 712.5 kB/s eta 0:00:06
   ------------------------ --------------- 6.3/10.2 MB 715.9 kB/s eta 0:00:06
   ------------------------- -------------- 6.6/10.2 MB 715.2 kB/s eta 0:00:06
   ------------------------- -------------- 6.6/10.2 MB 715.2 kB/s eta 0:00:06
   ------------------------- -------------- 6.6/10.2 MB 715.2 kB/s eta 0:00:06
   -------------------------- ------------- 6.8/10.2 MB 706.1 kB/s eta 0:00:05
   --------------------------- ------------ 7.1/10.2 MB 710.4 kB/s eta 0:00:05
   --------------------------- ------------ 7.1/10.2 MB 710.4 kB/s eta 0:00:05
   ---------------------------- ----------- 7.3/10.2 MB 707.8 kB/s eta 0:00:05
   ---------------------------- ----------- 7.3/10.2 MB 707.8 kB/s eta 0:00:05
   ----------------------------- ---------- 7.6/10.2 MB 705.4 kB/s eta 0:00:04
   ----------------------------- ---------- 7.6/10.2 MB 705.4 kB/s eta 0:00:04
   ------------------------------ --------- 7.9/10.2 MB 702.1 kB/s eta 0:00:04
   ------------------------------ --------- 7.9/10.2 MB 702.1 kB/s eta 0:00:04
   ------------------------------- -------- 8.1/10.2 MB 699.0 kB/s eta 0:00:04
   ------------------------------- -------- 8.1/10.2 MB 699.0 kB/s eta 0:00:04
   ------------------------------- -------- 8.1/10.2 MB 699.0 kB/s eta 0:00:04
   ------------------------------- -------- 8.1/10.2 MB 699.0 kB/s eta 0:00:04
   --------------------------------- ------ 8.7/10.2 MB 690.1 kB/s eta 0:00:03
   --------------------------------- ------ 8.7/10.2 MB 690.1 kB/s eta 0:00:03
   ---------------------------------- ----- 8.9/10.2 MB 692.9 kB/s eta 0:00:02
   ---------------------------------- ----- 8.9/10.2 MB 692.9 kB/s eta 0:00:02
   ----------------------------------- ---- 9.2/10.2 MB 688.9 kB/s eta 0:00:02
   ------------------------------------ --- 9.4/10.2 MB 693.3 kB/s eta 0:00:02
   ------------------------------------ --- 9.4/10.2 MB 693.3 kB/s eta 0:00:02
   ------------------------------------ --- 9.4/10.2 MB 693.3 kB/s eta 0:00:02
   ------------------------------------- -- 9.7/10.2 MB 686.3 kB/s eta 0:00:01
   ------------------------------------- -- 9.7/10.2 MB 686.3 kB/s eta 0:00:01
   -------------------------------------- - 10.0/10.2 MB 685.2 kB/s eta 0:00:01
   -------------------------------------- - 10.0/10.2 MB 685.2 kB/s eta 0:00:01
   ---------------------------------------- 10.2/10.2 MB 681.2 kB/s  0:00:14
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.7 MB 799.2 kB/s eta 0:00:03
   ------- -------------------------------- 0.5/2.7 MB 799.2 kB/s eta 0:00:03
   ----------- ---------------------------- 0.8/2.7 MB 838.9 kB/s eta 0:00:03
   ----------- ---------------------------- 0.8/2.7 MB 838.9 kB/s eta 0:00:03
   --------------- ------------------------ 1.0/2.7 MB 762.8 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.7 MB 789.6 kB/s eta 0:00:02
   ------------------- -------------------- 1.3/2.7 MB 789.6 kB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.7 MB 798.7 kB/s eta 0:00:02
   -------------------------- ------------- 1.8/2.7 MB 805.4 kB/s eta 0:00:02
   -------------------------- ------------- 1.8/2.7 MB 805.4 kB/s eta 0:00:02
   ------------------------------ --------- 2.1/2.7 MB 809.8 kB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 809.8 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.7 MB 758.2 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.7 MB 758.2 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 743.8 kB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 739.8 kB/s  0:00:03
Downloading sentencepiece-0.2.1-cp311-cp311-win_amd64.whl (1.1 MB)
   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   --------- ------------------------------ 0.3/1.1 MB ? eta -:--:--
   ------------------- -------------------- 0.5/1.1 MB 882.6 kB/s eta 0:00:01
   ------------------- -------------------- 0.5/1.1 MB 882.6 kB/s eta 0:00:01
   ------------------- -------------------- 0.5/1.1 MB 882.6 kB/s eta 0:00:01
   ----------------------------- ---------- 0.8/1.1 MB 645.7 kB/s eta 0:00:01
   ---------------------------------------  1.0/1.1 MB 653.7 kB/s eta 0:00:01
   ---------------------------------------- 1.1/1.1 MB 642.2 kB/s  0:00:01
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Downloading regex-2026.4.4-cp311-cp311-win_amd64.whl (278 kB)
Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl (341 kB)
Installing collected packages: sentencepiece, safetensors, regex, h11, httpcore, httpx, tokenizers, transformers

   ----- ---------------------------------- 1/8 [safetensors]
   ---------- ----------------------------- 2/8 [regex]
   ---------- ----------------------------- 2/8 [regex]
  Attempting uninstall: h11
   ---------- ----------------------------- 2/8 [regex]
    Found existing installation: h11 0.9.0
   ---------- ----------------------------- 2/8 [regex]
    Uninstalling h11-0.9.0:
   ---------- ----------------------------- 2/8 [regex]
      Successfully uninstalled h11-0.9.0
   ---------- ----------------------------- 2/8 [regex]
   --------------- ------------------------ 3/8 [h11]
   --------------- ------------------------ 3/8 [h11]
   --------------- ------------------------ 3/8 [h11]
  Attempting uninstall: httpcore
   --------------- ------------------------ 3/8 [h11]
    Found existing installation: httpcore 0.9.1
   --------------- ------------------------ 3/8 [h11]
    Uninstalling httpcore-0.9.1:
   --------------- ------------------------ 3/8 [h11]
      Successfully uninstalled httpcore-0.9.1
   --------------- ------------------------ 3/8 [h11]
   -------------------- ------------------- 4/8 [httpcore]
   -------------------- ------------------- 4/8 [httpcore]
   -------------------- ------------------- 4/8 [httpcore]
   -------------------- ------------------- 4/8 [httpcore]
  Attempting uninstall: httpx
   -------------------- ------------------- 4/8 [httpcore]
    Found existing installation: httpx 0.13.3
   -------------------- ------------------- 4/8 [httpcore]
    Uninstalling httpx-0.13.3:
   -------------------- ------------------- 4/8 [httpcore]
   ------------------------- -------------- 5/8 [httpx]
      Successfully uninstalled httpx-0.13.3
   ------------------------- -------------- 5/8 [httpx]
   ------------------------- -------------- 5/8 [httpx]
   ------------------------- -------------- 5/8 [httpx]
   ------------------------- -------------- 5/8 [httpx]
   ------------------------- -------------- 5/8 [httpx]
   ------------------------------ --------- 6/8 [tokenizers]
   ------------------------------ --------- 6/8 [tokenizers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]
   ----------------------------------- ---- 7/8 [transformers]

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
googletrans 4.0.0rc1 requires httpx==0.13.3, but you have httpx 0.28.1 which is incompatible.

In [11]:
import sys
!{sys.executable} -m pip install transformers datasets sentencepiece torch

Requirement already satisfied: transformers in E:\conda\envs\mental_env\Lib\site-packages (5.5.0)
Requirement already satisfied: datasets in E:\conda\envs\mental_env\Lib\site-packages (4.8.4)
Requirement already satisfied: sentencepiece in E:\conda\envs\mental_env\Lib\site-packages (0.2.1)
Collecting torch
  Downloading torch-2.11.0-cp311-cp311-win_amd64.whl.metadata (29 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (1.9.0)
Requirement already satisfied: numpy>=1.17 in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (2.4.4)
Requirement already satisfied: packaging>=20.0 in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in E:\conda\envs\mental_env\Lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2.10)
Requirement already satisfied: h11>=0.16 in E:\conda\envs\mental_env\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: pyarrow>=21.0.0 in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (3.0.2)
Requirement already satisfied: requests>=2.32.2 in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (2.33.1)
Requirement already satisfied: xxhash in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in E:\conda\envs\mental_env\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in E:\conda\envs\mental_env\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Collecting setuptools<82 (from torch)
  Downloading setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in E:\conda\envs\mental_env\Lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in E:\conda\envs\mental_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in E:\conda\envs\mental_env\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.26 in E:\conda\envs\mental_env\Lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: colorama in E:\conda\envs\mental_env\Lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in E:\conda\envs\mental_env\Lib\site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in E:\conda\envs\mental_env\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in E:\conda\envs\mental_env\Lib\site-packages (from pandas->datasets) (2026.1)
Requirement already satisfied: six>=1.5 in E:\conda\envs\mental_env\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in E:\conda\envs\mental_env\Lib\site-packages (from typer->transformers) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in E:\conda\envs\mental_env\Lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in E:\conda\envs\mental_env\Lib\site-packages (from typer->transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in E:\conda\envs\mental_env\Lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in E:\conda\envs\mental_env\Lib\site-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in E:\conda\envs\mental_env\Lib\site-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in E:\conda\envs\mental_env\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading torch-2.11.0-cp311-cp311-win_amd64.whl (114.5 MB)
   ---------------------------------------- 0.0/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/114.5 MB ? eta -:--:--
   ---------------------------------------- 0.5/114.5 MB 258.3 kB/s eta 0:07:22
   ---------------------------------------- 0.5/114.5 MB 258.3 kB/s eta 0:07:22
   ---------------------------------------- 0.5/114.5 MB 258.3 kB/s eta 0:07:22
   ---------------------------------------- 0.8/114.5 MB 313.6 kB/s eta 0:06:03
   ---------------------------------------- 0.8/114.5 MB 313.6 kB/s eta 0:06:03
   ---------------------------------------- 0.8/114.5 MB 313.6 kB/s eta 0:06:03
   ---------------------------------------- 0.8/114.5 MB 313.6 kB/s eta 0:06:03
   ---------------------------------------- 1.0/114.5 MB 331.1 kB/s eta 0:05:43
   ---------------------------------------- 1.0/114.5 MB 331.1 kB/s eta 0:05:43
   ---------------------------------------- 1.3/114.5 MB 351.4 kB/s eta 0:05:23
   ---------------------------------------- 1.3/114.5 MB 351.4 kB/s eta 0:05:23
    --------------------------------------- 1.6/114.5 MB 395.7 kB/s eta 0:04:46
    --------------------------------------- 1.6/114.5 MB 395.7 kB/s eta 0:04:46
    --------------------------------------- 1.8/114.5 MB 428.3 kB/s eta 0:04:24
    --------------------------------------- 1.8/114.5 MB 428.3 kB/s eta 0:04:24
    --------------------------------------- 2.1/114.5 MB 448.3 kB/s eta 0:04:11
    --------------------------------------- 2.1/114.5 MB 448.3 kB/s eta 0:04:11
    --------------------------------------- 2.4/114.5 MB 458.1 kB/s eta 0:04:05
    --------------------------------------- 2.4/114.5 MB 458.1 kB/s eta 0:04:05
    --------------------------------------- 2.6/114.5 MB 476.3 kB/s eta 0:03:55
    --------------------------------------- 2.6/114.5 MB 476.3 kB/s eta 0:03:55
   - -------------------------------------- 2.9/114.5 MB 489.2 kB/s eta 0:03:49
   - -------------------------------------- 3.1/114.5 MB 507.0 kB/s eta 0:03:40
   - -------------------------------------- 3.1/114.5 MB 507.0 kB/s eta 0:03:40
   - -------------------------------------- 3.4/114.5 MB 524.3 kB/s eta 0:03:32
   - -------------------------------------- 3.7/114.5 MB 539.9 kB/s eta 0:03:26
   - -------------------------------------- 3.9/114.5 MB 555.3 kB/s eta 0:03:20
   - -------------------------------------- 3.9/114.5 MB 555.3 kB/s eta 0:03:20
   - -------------------------------------- 4.2/114.5 MB 568.1 kB/s eta 0:03:15
   - -------------------------------------- 4.5/114.5 MB 579.8 kB/s eta 0:03:10
   - -------------------------------------- 4.5/114.5 MB 579.8 kB/s eta 0:03:10
   - -------------------------------------- 4.7/114.5 MB 591.7 kB/s eta 0:03:06
   - -------------------------------------- 5.0/114.5 MB 600.4 kB/s eta 0:03:03
   - -------------------------------------- 5.0/114.5 MB 600.4 kB/s eta 0:03:03
   - -------------------------------------- 5.2/114.5 MB 603.7 kB/s eta 0:03:02
   - -------------------------------------- 5.5/114.5 MB 613.4 kB/s eta 0:02:58
   - -------------------------------------- 5.5/114.5 MB 613.4 kB/s eta 0:02:58
   -- ------------------------------------- 5.8/114.5 MB 621.4 kB/s eta 0:02:56
   -- ------------------------------------- 6.0/114.5 MB 628.8 kB/s eta 0:02:53
   -- ------------------------------------- 6.0/114.5 MB 628.8 kB/s eta 0:02:53
   -- ------------------------------------- 6.0/114.5 MB 628.8 kB/s eta 0:02:53
   -- ------------------------------------- 6.0/114.5 MB 628.8 kB/s eta 0:02:53
   -- ------------------------------------- 6.3/114.5 MB 597.4 kB/s eta 0:03:02
   -- ------------------------------------- 6.8/114.5 MB 639.4 kB/s eta 0:02:49
   -- ------------------------------------- 6.8/114.5 MB 639.4 kB/s eta 0:02:49
   -- ------------------------------------- 7.1/114.5 MB 641.5 kB/s eta 0:02:48
   -- ------------------------------------- 7.1/114.5 MB 641.5 kB/s eta 0:02:48
   -- ------------------------------------- 7.3/114.5 MB 638.9 kB/s eta 0:02:48
   -- ------------------------------------- 7.3/114.5 MB 638.9 kB/s eta 0:02:48
   -- ------------------------------------- 7.6/114.5 MB 644.4 kB/s eta 0:02:46
   -- ------------------------------------- 7.9/114.5 MB 644.4 kB/s eta 0:02:46
   -- ------------------------------------- 7.9/114.5 MB 644.4 kB/s eta 0:02:46
   -- ------------------------------------- 8.1/114.5 MB 647.8 kB/s eta 0:02:45
   -- ------------------------------------- 8.4/114.5 MB 652.6 kB/s eta 0:02:43
   -- ------------------------------------- 8.4/114.5 MB 652.6 kB/s eta 0:02:43
   -- ------------------------------------- 8.4/114.5 MB 652.6 kB/s eta 0:02:43
   -- ------------------------------------- 8.4/114.5 MB 652.6 kB/s eta 0:02:43
   -- ------------------------------------- 8.4/114.5 MB 652.6 kB/s eta 0:02:43
   --- ------------------------------------ 8.9/114.5 MB 649.8 kB/s eta 0:02:43
   --- ------------------------------------ 9.2/114.5 MB 654.9 kB/s eta 0:02:41
   --- ------------------------------------ 9.4/114.5 MB 659.8 kB/s eta 0:02:40
   --- ------------------------------------ 9.4/114.5 MB 659.8 kB/s eta 0:02:40
   --- ------------------------------------ 9.4/114.5 MB 659.8 kB/s eta 0:02:40
   --- ------------------------------------ 9.7/114.5 MB 655.8 kB/s eta 0:02:40
   --- ----------------------------------- 10.0/114.5 MB 659.0 kB/s eta 0:02:39
   --- ----------------------------------- 10.0/114.5 MB 659.0 kB/s eta 0:02:39
   --- ----------------------------------- 10.2/114.5 MB 656.6 kB/s eta 0:02:39
   --- ----------------------------------- 10.2/114.5 MB 656.6 kB/s eta 0:02:39
   --- ----------------------------------- 10.2/114.5 MB 656.6 kB/s eta 0:02:39
   --- ----------------------------------- 10.2/114.5 MB 656.6 kB/s eta 0:02:39
   --- ----------------------------------- 10.7/114.5 MB 656.7 kB/s eta 0:02:39
   --- ----------------------------------- 11.0/114.5 MB 660.8 kB/s eta 0:02:37
   --- ----------------------------------- 11.0/114.5 MB 660.8 kB/s eta 0:02:37
   --- ----------------------------------- 11.3/114.5 MB 664.1 kB/s eta 0:02:36
   --- ----------------------------------- 11.5/114.5 MB 667.4 kB/s eta 0:02:35
   ---- ---------------------------------- 11.8/114.5 MB 670.5 kB/s eta 0:02:34
   ---- ---------------------------------- 11.8/114.5 MB 670.5 kB/s eta 0:02:34
   ---- ---------------------------------- 12.1/114.5 MB 669.9 kB/s eta 0:02:33
   ---- ---------------------------------- 12.1/114.5 MB 669.9 kB/s eta 0:02:33
   ---- ---------------------------------- 12.3/114.5 MB 668.8 kB/s eta 0:02:33
   ---- ---------------------------------- 12.3/114.5 MB 668.8 kB/s eta 0:02:33
   ---- ---------------------------------- 12.6/114.5 MB 672.2 kB/s eta 0:02:32
   ---- ---------------------------------- 12.8/114.5 MB 675.0 kB/s eta 0:02:31
   ---- ---------------------------------- 13.1/114.5 MB 677.7 kB/s eta 0:02:30
   ---- ---------------------------------- 13.1/114.5 MB 677.7 kB/s eta 0:02:30
   ---- ---------------------------------- 13.4/114.5 MB 680.9 kB/s eta 0:02:29
   ---- ---------------------------------- 13.6/114.5 MB 684.0 kB/s eta 0:02:28
   ---- ---------------------------------- 13.6/114.5 MB 684.0 kB/s eta 0:02:28
   ---- ---------------------------------- 13.9/114.5 MB 686.4 kB/s eta 0:02:27
   ---- ---------------------------------- 14.2/114.5 MB 688.8 kB/s eta 0:02:26
   ---- ---------------------------------- 14.4/114.5 MB 691.1 kB/s eta 0:02:25
   ---- ---------------------------------- 14.4/114.5 MB 691.1 kB/s eta 0:02:25
   ---- ---------------------------------- 14.7/114.5 MB 693.8 kB/s eta 0:02:24
   ----- --------------------------------- 14.9/114.5 MB 696.0 kB/s eta 0:02:24
   ----- --------------------------------- 14.9/114.5 MB 696.0 kB/s eta 0:02:24
   ----- --------------------------------- 15.2/114.5 MB 698.6 kB/s eta 0:02:23
   ----- --------------------------------- 15.5/114.5 MB 700.6 kB/s eta 0:02:22
   ----- --------------------------------- 15.7/114.5 MB 703.0 kB/s eta 0:02:21
   ----- --------------------------------- 15.7/114.5 MB 703.0 kB/s eta 0:02:21
   ----- --------------------------------- 16.0/114.5 MB 703.0 kB/s eta 0:02:21
   ----- --------------------------------- 16.3/114.5 MB 704.8 kB/s eta 0:02:20
   ----- --------------------------------- 16.3/114.5 MB 704.8 kB/s eta 0:02:20
   ----- --------------------------------- 16.5/114.5 MB 707.1 kB/s eta 0:02:19
   ----- --------------------------------- 16.8/114.5 MB 709.4 kB/s eta 0:02:18
   ----- --------------------------------- 16.8/114.5 MB 709.4 kB/s eta 0:02:18
   ----- --------------------------------- 17.0/114.5 MB 711.1 kB/s eta 0:02:18
   ----- --------------------------------- 17.3/114.5 MB 713.2 kB/s eta 0:02:17
   ----- --------------------------------- 17.6/114.5 MB 714.8 kB/s eta 0:02:16
   ----- --------------------------------- 17.6/114.5 MB 714.8 kB/s eta 0:02:16
   ------ -------------------------------- 17.8/114.5 MB 716.9 kB/s eta 0:02:15
   ------ -------------------------------- 18.1/114.5 MB 718.4 kB/s eta 0:02:15
   ------ -------------------------------- 18.1/114.5 MB 718.4 kB/s eta 0:02:15
   ------ -------------------------------- 18.4/114.5 MB 720.4 kB/s eta 0:02:14
   ------ -------------------------------- 18.6/114.5 MB 721.8 kB/s eta 0:02:13
   ------ -------------------------------- 18.9/114.5 MB 723.7 kB/s eta 0:02:13
   ------ -------------------------------- 18.9/114.5 MB 723.7 kB/s eta 0:02:13
   ------ -------------------------------- 19.1/114.5 MB 725.5 kB/s eta 0:02:12
   ------ -------------------------------- 19.4/114.5 MB 726.9 kB/s eta 0:02:11
   ------ -------------------------------- 19.4/114.5 MB 726.9 kB/s eta 0:02:11
   ------ -------------------------------- 19.7/114.5 MB 728.6 kB/s eta 0:02:11
   ------ -------------------------------- 19.9/114.5 MB 729.9 kB/s eta 0:02:10
   ------ -------------------------------- 20.2/114.5 MB 731.5 kB/s eta 0:02:09
   ------ -------------------------------- 20.2/114.5 MB 731.5 kB/s eta 0:02:09
   ------ -------------------------------- 20.4/114.5 MB 732.8 kB/s eta 0:02:09
   ------- ------------------------------- 20.7/114.5 MB 734.4 kB/s eta 0:02:08
   ------- ------------------------------- 20.7/114.5 MB 734.4 kB/s eta 0:02:08
   ------- ------------------------------- 21.0/114.5 MB 735.5 kB/s eta 0:02:08
   ------- ------------------------------- 21.2/114.5 MB 737.1 kB/s eta 0:02:07
   ------- ------------------------------- 21.5/114.5 MB 738.2 kB/s eta 0:02:07
   ------- ------------------------------- 21.5/114.5 MB 738.2 kB/s eta 0:02:07
   ------- ------------------------------- 21.8/114.5 MB 739.7 kB/s eta 0:02:06
   ------- ------------------------------- 22.0/114.5 MB 740.7 kB/s eta 0:02:05
   ------- ------------------------------- 22.0/114.5 MB 740.7 kB/s eta 0:02:05
   ------- ------------------------------- 22.3/114.5 MB 742.1 kB/s eta 0:02:05
   ------- ------------------------------- 22.3/114.5 MB 742.1 kB/s eta 0:02:05
   ------- ------------------------------- 22.3/114.5 MB 742.1 kB/s eta 0:02:05
   ------- ------------------------------- 22.8/114.5 MB 756.1 kB/s eta 0:02:02
   ------- ------------------------------- 23.1/114.5 MB 762.6 kB/s eta 0:02:00
   ------- ------------------------------- 23.3/114.5 MB 763.4 kB/s eta 0:02:00
   ------- ------------------------------- 23.3/114.5 MB 763.4 kB/s eta 0:02:00
   -------- ------------------------------ 23.6/114.5 MB 772.7 kB/s eta 0:01:58
   -------- ------------------------------ 23.9/114.5 MB 773.4 kB/s eta 0:01:58
   -------- ------------------------------ 24.1/114.5 MB 783.7 kB/s eta 0:01:56
   -------- ------------------------------ 24.1/114.5 MB 783.7 kB/s eta 0:01:56

In [14]:
!pip install -U accelerate

ERROR: Could not find a version that satisfies the requirement accelerate (from versions: none)
ERROR: No matching distribution found for accelerate

In [15]:
!pip install -U accelerate

Collecting accelerate
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in E:\conda\envs\mental_env\Lib\site-packages (from accelerate) (2.4.4)
Requirement already satisfied: packaging>=20.0 in E:\conda\envs\mental_env\Lib\site-packages (from accelerate) (26.0)
Requirement already satisfied: psutil in E:\conda\envs\mental_env\Lib\site-packages (from accelerate) (7.0.0)
Requirement already satisfied: pyyaml in E:\conda\envs\mental_env\Lib\site-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in E:\conda\envs\mental_env\Lib\site-packages (from accelerate) (2.11.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in E:\conda\envs\mental_env\Lib\site-packages (from accelerate) (1.9.0)
Requirement already satisfied: safetensors>=0.4.3 in E:\conda\envs\mental_env\Lib\site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typer in E:\conda\envs\mental_env\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: anyio in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.12.1)
Requirement already satisfied: certifi in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.1.4)
Requirement already satisfied: httpcore==1.* in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2.10)
Requirement already satisfied: h11>=0.16 in E:\conda\envs\mental_env\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: setuptools<82 in E:\conda\envs\mental_env\Lib\site-packages (from torch>=2.0.0->accelerate) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in E:\conda\envs\mental_env\Lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in E:\conda\envs\mental_env\Lib\site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in E:\conda\envs\mental_env\Lib\site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in E:\conda\envs\mental_env\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: colorama in E:\conda\envs\mental_env\Lib\site-packages (from tqdm>=4.42.1->huggingface_hub>=0.21.0->accelerate) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in E:\conda\envs\mental_env\Lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.2)
Requirement already satisfied: click>=8.2.1 in E:\conda\envs\mental_env\Lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in E:\conda\envs\mental_env\Lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in E:\conda\envs\mental_env\Lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in E:\conda\envs\mental_env\Lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in E:\conda\envs\mental_env\Lib\site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in E:\conda\envs\mental_env\Lib\site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in E:\conda\envs\mental_env\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (0.1.2)
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.13.0

In [17]:
import sys
!{sys.executable} -m pip install -U accelerate transformers[torch]

Requirement already satisfied: accelerate in E:\conda\envs\mental_env\Lib\site-packages (1.13.0)
Requirement already satisfied: transformers[torch] in E:\conda\envs\mental_env\Lib\site-packages (5.5.0)
Requirement already satisfied: numpy>=1.17 in E:\conda\envs\mental_env\Lib\site-packages (from accelerate) (2.4.4)
Requirement already satisfied: packaging>=20.0 in E:\conda\envs\mental_env\Lib\site-packages (from accelerate) (26.0)
Requirement already satisfied: psutil in E:\conda\envs\mental_env\Lib\site-packages (from accelerate) (7.0.0)
Requirement already satisfied: pyyaml in E:\conda\envs\mental_env\Lib\site-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in E:\conda\envs\mental_env\Lib\site-packages (from accelerate) (2.11.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in E:\conda\envs\mental_env\Lib\site-packages (from accelerate) (1.9.0)
Requirement already satisfied: safetensors>=0.4.3 in E:\conda\envs\mental_env\Lib\site-packages (from accelerate) (0.7.0)
Requirement already satisfied: regex>=2025.10.22 in E:\conda\envs\mental_env\Lib\site-packages (from transformers[torch]) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in E:\conda\envs\mental_env\Lib\site-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: typer in E:\conda\envs\mental_env\Lib\site-packages (from transformers[torch]) (0.24.1)
Requirement already satisfied: tqdm>=4.27 in E:\conda\envs\mental_env\Lib\site-packages (from transformers[torch]) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in E:\conda\envs\mental_env\Lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: anyio in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.12.1)
Requirement already satisfied: certifi in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.1.4)
Requirement already satisfied: httpcore==1.* in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in E:\conda\envs\mental_env\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2.10)
Requirement already satisfied: h11>=0.16 in E:\conda\envs\mental_env\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: setuptools<82 in E:\conda\envs\mental_env\Lib\site-packages (from torch>=2.0.0->accelerate) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in E:\conda\envs\mental_env\Lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in E:\conda\envs\mental_env\Lib\site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in E:\conda\envs\mental_env\Lib\site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in E:\conda\envs\mental_env\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: colorama in E:\conda\envs\mental_env\Lib\site-packages (from tqdm>=4.27->transformers[torch]) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in E:\conda\envs\mental_env\Lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.2)
Requirement already satisfied: click>=8.2.1 in E:\conda\envs\mental_env\Lib\site-packages (from typer->transformers[torch]) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in E:\conda\envs\mental_env\Lib\site-packages (from typer->transformers[torch]) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in E:\conda\envs\mental_env\Lib\site-packages (from typer->transformers[torch]) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in E:\conda\envs\mental_env\Lib\site-packages (from typer->transformers[torch]) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in E:\conda\envs\mental_env\Lib\site-packages (from rich>=12.3.0->typer->transformers[torch]) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in E:\conda\envs\mental_env\Lib\site-packages (from rich>=12.3.0->typer->transformers[torch]) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in E:\conda\envs\mental_env\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers[torch]) (0.1.2)

In [35]:

import os, pickle, warnings, numpy as np, pandas as pd, torch
from datasets import Dataset
from transformers import (
    AutoTokenizer, AutoModelForSequenceClassification,
    Trainer, TrainingArguments, EarlyStoppingCallback,
    DataCollatorWithPadding,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import accuracy_score, f1_score, classification_report
warnings.filterwarnings("ignore")

# ── CONFIG ──────────────────────────────────────────────────────────
CSV_PATH    = "/kaggle/input/datasets/tasneem33355/data33/MentalHealth_Darija.csv"
CKPT_PATH   = "./mental_xlmr_best"  
OUTPUT_DIR  = "./mental_xlmr_v2"
MAX_LEN     = 256
BATCH_SIZE  = 16
EPOCHS      = 6                      
LR          = 5e-6                   
SEED        = 42
LABEL_MAP   = {0: "anxiety", 2: "stress", 3: "depression"}

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"✅ Device: {device}")

# ── PREPROCESS  ────────────────────────────────────────
df = pd.read_csv(CSV_PATH)
df = df[['text', 'text_en', 'label']].dropna()
df['combined_text'] = df['text_en'].str.strip() + " [SEP] " + df['text'].str.strip()
df_filtered = df[df['label'].isin(LABEL_MAP.keys())].copy()
df_filtered['target'] = df_filtered['label'].map(LABEL_MAP)

le = LabelEncoder()
df_filtered['label_encoded'] = le.fit_transform(df_filtered['target'])

X_train, X_val, y_train, y_val = train_test_split(
    df_filtered['combined_text'].values,
    df_filtered['label_encoded'].values,
    test_size=0.2, random_state=SEED,
    stratify=df_filtered['label_encoded'],
)
print(f"Train: {len(X_train)} | Val: {len(X_val)}")

# ── DATASETS ────────────────────────────────────────────────────────
tokenizer = AutoTokenizer.from_pretrained(CKPT_PATH)

def tokenize(batch):
    return tokenizer(batch["text"], padding=False,
                     truncation=True, max_length=MAX_LEN)

train_hf = Dataset.from_dict({"text": list(X_train), "labels": list(y_train)})
val_hf   = Dataset.from_dict({"text": list(X_val),   "labels": list(y_val)})
train_hf = train_hf.map(tokenize, batched=True, remove_columns=["text"])
val_hf   = val_hf.map(tokenize,   batched=True, remove_columns=["text"])
train_hf.set_format("torch", columns=["input_ids", "attention_mask", "labels"])
val_hf.set_format("torch",   columns=["input_ids", "attention_mask", "labels"])

# ── CLASS WEIGHTS ──────────────────────────────────────────
unique_labels = np.unique(y_train)
num_labels    = len(unique_labels)
class_weights = compute_class_weight("balanced", classes=unique_labels, y=y_train)

# stress index = 2
class_weights[1] *= 1.4   # boost depression
class_weights[2] *= 1.2   # boost stress قليلاً
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)

print("⚖️  Adjusted class weights:")
for i, c in enumerate(le.classes_):
    print(f"   {c}: {class_weights[i]:.3f}")

# ── MODEL ────────────────────────────────────────
model = AutoModelForSequenceClassification.from_pretrained(CKPT_PATH)
model = model.to(device)


for name, param in model.named_parameters():
    if any(f"layer.{i}" in name for i in range(9)):
        param.requires_grad = False
    else:
        param.requires_grad = True

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total     = sum(p.numel() for p in model.parameters())
print(f"\n🔧 Trainable params: {trainable:,} / {total:,} ({100*trainable/total:.1f}%)")

# ── WEIGHTED TRAINER ────────────────────────────────────────────────
class WeightedTrainer(Trainer):
    def __init__(self, class_weights, **kwargs):
        super().__init__(**kwargs)
        self.class_weights = class_weights

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels  = inputs.pop("labels")
        outputs = model(**inputs)
        loss    = torch.nn.CrossEntropyLoss(weight=self.class_weights)(
            outputs.logits, labels
        )
        return (loss, outputs) if return_outputs else loss

# ── METRICS ─────────────────────────────────────────────────────────
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": round(accuracy_score(labels, preds), 4),
        "f1_macro": round(f1_score(labels, preds, average="macro"), 4),
    }

# ── TRAINING ARGS ───────────────────────────────────────────────────
total_steps  = (len(train_hf) // BATCH_SIZE) * EPOCHS
warmup_steps = int(total_steps * 0.05)   

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=EPOCHS,
    learning_rate=LR,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE * 2,
    weight_decay=0.01,
    warmup_steps=warmup_steps,
    lr_scheduler_type="cosine",
    logging_steps=50,
    save_strategy="epoch",
    eval_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    greater_is_better=True,
    fp16=torch.cuda.is_available(),
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    dataloader_num_workers=2,
    report_to="none",
    seed=SEED,
)

# ── TRAINER ─────────────────────────────────────────────────────────
trainer = WeightedTrainer(
    class_weights=class_weights_tensor,
    model=model,
    args=training_args,
    train_dataset=train_hf,
    eval_dataset=val_hf,
    compute_metrics=compute_metrics,
    data_collator=DataCollatorWithPadding(tokenizer=tokenizer),
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

# ── TRAIN ────────────────────────────────────────────────────────────
print("\n🚀 Continuing training from checkpoint...")
trainer.train()

# ── FINAL EVAL ───────────────────────────────────────────────────────
results = trainer.evaluate()
print("\n📊 Final Evaluation:")
for k, v in results.items():
    if isinstance(v, float): print(f"   {k}: {round(v,4)}")

raw_preds = trainer.predict(val_hf)
preds     = np.argmax(raw_preds.predictions, axis=-1)
print("\n📋 Classification Report:")
print(classification_report(y_val, preds, target_names=le.classes_))

# ── SAVE ─────────────────────────────────────────────────────────────
os.makedirs(OUTPUT_DIR, exist_ok=True)
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
with open(os.path.join(OUTPUT_DIR, "label_encoder.pkl"), "wb") as f:
    pickle.dump(le, f)

print(f"\n✅ v2 saved to {OUTPUT_DIR}")

✅ Device: cuda
Train: 23488 | Val: 5873

Map:   0%|          | 0/23488 [00:00<?, ? examples/s]

Map:   0%|          | 0/5873 [00:00<?, ? examples/s]

⚖️  Adjusted class weights:
   anxiety: 2.702
   depression: 1.287
   stress: 0.778

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

🔧 Trainable params: 200,079,363 / 278,045,955 (72.0%)

🚀 Continuing training from checkpoint...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

📊 Final Evaluation:
   eval_loss: 0.4215
   eval_accuracy: 0.8001
   eval_f1_macro: 0.835
   eval_runtime: 54.2312
   eval_samples_per_second: 108.296
   eval_steps_per_second: 1.696
   epoch: 4.0

📋 Classification Report:
              precision    recall  f1-score   support

     anxiety       0.94      0.97      0.95       725
  depression       0.70      0.83      0.76      2129
      stress       0.85      0.74      0.79      3019

    accuracy                           0.80      5873
   macro avg       0.83      0.84      0.83      5873
weighted avg       0.81      0.80      0.80      5873

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

✅ v2 saved to ./mental_xlmr_v2

In [3]:
import os, pickle, warnings, numpy as np, pandas as pd, torch, zipfile
from datasets import Dataset
from transformers import (
    AutoTokenizer, AutoModelForSequenceClassification,
    Trainer, TrainingArguments, EarlyStoppingCallback,
    DataCollatorWithPadding,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import accuracy_score, f1_score, classification_report
from IPython.display import FileLink
warnings.filterwarnings("ignore")

CSV_PATH   = "/kaggle/input/datasets/tasneem33355/data33/MentalHealth_Darija.csv"
MODEL_NAME = "xlm-roberta-base"
OUTPUT_DIR = "/kaggle/working/mental_xlmr_final"
MAX_LEN    = 256
BATCH_SIZE = 16
EPOCHS     = 6
LR         = 2e-5
SEED       = 42
LABEL_MAP  = {0: "anxiety", 2: "stress", 3: "depression"}

torch.manual_seed(SEED)
np.random.seed(SEED)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

df = pd.read_csv(CSV_PATH)
df = df[['text', 'text_en', 'label']].dropna()
df['combined_text'] = df['text_en'].str.strip() + " [SEP] " + df['text'].str.strip()
df_filtered = df[df['label'].isin(LABEL_MAP.keys())].copy()
df_filtered['target'] = df_filtered['label'].map(LABEL_MAP)

print("\nClass distribution:")
print(df_filtered['target'].value_counts())

le = LabelEncoder()
df_filtered['label_encoded'] = le.fit_transform(df_filtered['target'])
print(f"Classes: {le.classes_}")

X_train, X_val, y_train, y_val = train_test_split(
    df_filtered['combined_text'].values,
    df_filtered['label_encoded'].values,
    test_size=0.2, random_state=SEED,
    stratify=df_filtered['label_encoded'],
)
print(f"Train: {len(X_train)} | Val: {len(X_val)}")

unique_labels = np.unique(y_train)
class_weights = compute_class_weight("balanced", classes=unique_labels, y=y_train)
class_weights[1] *= 1.4
class_weights[2] *= 1.2
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)

print("\nClass weights:")
for i, c in enumerate(le.classes_):
    print(f"  {c}: {class_weights[i]:.3f}")

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize(batch):
    return tokenizer(batch["text"], padding=False, truncation=True, max_length=MAX_LEN)

train_hf = Dataset.from_dict({"text": list(X_train), "labels": list(y_train)})
val_hf   = Dataset.from_dict({"text": list(X_val),   "labels": list(y_val)})
train_hf = train_hf.map(tokenize, batched=True, remove_columns=["text"])
val_hf   = val_hf.map(tokenize,   batched=True, remove_columns=["text"])
train_hf.set_format("torch", columns=["input_ids", "attention_mask", "labels"])
val_hf.set_format("torch",   columns=["input_ids", "attention_mask", "labels"])

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME, num_labels=3, ignore_mismatched_sizes=True,
)
model = model.to(device)
print(f"Params: {sum(p.numel() for p in model.parameters()):,}")

class WeightedTrainer(Trainer):
    def __init__(self, class_weights, **kwargs):
        super().__init__(**kwargs)
        self.class_weights = class_weights

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels  = inputs.pop("labels")
        outputs = model(**inputs)
        loss = torch.nn.CrossEntropyLoss(weight=self.class_weights)(outputs.logits, labels)
        return (loss, outputs) if return_outputs else loss

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": round(accuracy_score(labels, preds), 4),
        "f1_macro": round(f1_score(labels, preds, average="macro"), 4),
    }

total_steps  = (len(train_hf) // BATCH_SIZE) * EPOCHS
warmup_steps = int(total_steps * 0.05)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=EPOCHS,
    learning_rate=LR,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=32,
    weight_decay=0.01,
    warmup_steps=warmup_steps,
    lr_scheduler_type="cosine",
    logging_steps=50,
    save_strategy="epoch",
    eval_strategy="epoch",
    save_total_limit=1,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    greater_is_better=True,
    fp16=True,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    dataloader_num_workers=2,
    report_to="none",
    seed=SEED,
    save_only_model=True,
)

trainer = WeightedTrainer(
    class_weights=class_weights_tensor,
    model=model,
    args=training_args,
    train_dataset=train_hf,
    eval_dataset=val_hf,
    compute_metrics=compute_metrics,
    data_collator=DataCollatorWithPadding(tokenizer=tokenizer),
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
)

print("\nStarting training...")
trainer.train()

results = trainer.evaluate()
print("\nFinal Evaluation:")
for k, v in results.items():
    if isinstance(v, float): print(f"  {k}: {round(v, 4)}")

raw_preds = trainer.predict(val_hf)
preds = np.argmax(raw_preds.predictions, axis=-1)
print("\nClassification Report:")
print(classification_report(y_val, preds, target_names=le.classes_))

os.makedirs(OUTPUT_DIR, exist_ok=True)
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
with open(os.path.join(OUTPUT_DIR, "label_encoder.pkl"), "wb") as f:
    pickle.dump(le, f)
print(f"\nSaved to {OUTPUT_DIR}")

zip_path = "/kaggle/working/mental_xlmr_final.zip"
with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
    for root, dirs, files in os.walk(OUTPUT_DIR):
        for file in files:
            file_path = os.path.join(root, file)
            zf.write(file_path, os.path.relpath(file_path, "/kaggle/working"))
print(f"Zip size: {os.path.getsize(zip_path)/1e9:.2f} GB")
FileLink(zip_path)

def predict_proba(texts: list) -> list:
    model.eval()
    out = []
    for text in texts:
        enc = tokenizer(text, return_tensors="pt", truncation=True, max_length=MAX_LEN).to(device)
        with torch.no_grad():
            probs = torch.softmax(model(**enc).logits, dim=-1).squeeze().cpu().numpy()
        out.append({c: round(float(p), 4) for c, p in zip(le.classes_, probs)})
    return out

print("\nSample prediction:")
print(predict_proba([X_val[0]]))

Device: cuda

Class distribution:
target
stress        15094
depression    10644
anxiety        3623
Name: count, dtype: int64
Classes: ['anxiety' 'depression' 'stress']
Train: 23488 | Val: 5873

Class weights:
  anxiety: 2.702
  depression: 1.287
  stress: 0.778

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/23488 [00:00<?, ? examples/s]

Map:   0%|          | 0/5873 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.weight        | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.dense.weight     | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Params: 278,045,955

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

Final Evaluation:
  eval_loss: 0.5114
  eval_accuracy: 0.7981
  eval_f1_macro: 0.8316
  eval_runtime: 50.7706
  eval_samples_per_second: 115.677
  eval_steps_per_second: 1.812
  epoch: 6.0

Classification Report:
              precision    recall  f1-score   support

     anxiety       0.94      0.96      0.95       725
  depression       0.72      0.77      0.74      2129
      stress       0.82      0.78      0.80      3019

    accuracy                           0.80      5873
   macro avg       0.83      0.84      0.83      5873
weighted avg       0.80      0.80      0.80      5873

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Saved to /kaggle/working/mental_xlmr_final
Zip size: 1.72 GB

Sample prediction:
[{'anxiety': 0.0002, 'depression': 0.9732, 'stress': 0.0265}]

In [7]:
from IPython.display import Javascript

JS = """
var link = document.createElement('a');
link.href = '/kaggle/working/mental_xlmr_final.zip';
link.download = 'mental_xlmr_final.zip';
document.body.appendChild(link);
link.click();
document.body.removeChild(link);
"""
display(Javascript(JS))